# USB output (required explicitly for split keyboards)
CONFIG_ZMK_USB=y

# Enable ZMK Studio (no locking so we can always connect)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Increase BT transmit power for better split connectivity
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
